name: Evidence Collection
on:
  workflow_dispatch:

jobs:
  aws-evidence:
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS credentials with OIDC
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: arn:aws:iam::145023120730:role/elevated-standards
        aws-region: us-east-1

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install boto3

